// Skill Institute design tokens — extracted from the Stitch design system (DESIGN.md)
export const colors = {
  surface: '#faf8ff',
  surfaceDim: '#d9d9e5',
  surfaceBright: '#faf8ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f3f3fe',
  surfaceContainer: '#ededf9',
  surfaceContainerHigh: '#e7e7f3',
  surfaceContainerHighest: '#e1e2ed',
  onSurface: '#191b23',
  onSurfaceVariant: '#434655',
  inverseSurface: '#2e3039',
  inverseOnSurface: '#f0f0fb',
  outline: '#737686',
  outlineVariant: '#c3c6d7',
  surfaceTint: '#0053db',
  primary: '#004ac6',
  onPrimary: '#ffffff',
  primaryContainer: '#2563eb',
  onPrimaryContainer: '#eeefff',
  inversePrimary: '#b4c5ff',
  secondary: '#505f76',
  onSecondary: '#ffffff',
  secondaryContainer: '#d0e1fb',
  onSecondaryContainer: '#54647a',
  tertiary: '#943700',
  onTertiary: '#ffffff',
  tertiaryContainer: '#bc4800',
  onTertiaryContainer: '#ffede6',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#dbe1ff',
  primaryFixedDim: '#b4c5ff',
  onPrimaryFixed: '#00174b',
  onPrimaryFixedVariant: '#003ea8',
  secondaryFixed: '#d3e4fe',
  secondaryFixedDim: '#b7c8e1',
  onSecondaryFixed: '#0b1c30',
  onSecondaryFixedVariant: '#38485d',
  tertiaryFixed: '#ffdbcd',
  tertiaryFixedDim: '#ffb596',
  onTertiaryFixed: '#360f00',
  onTertiaryFixedVariant: '#7d2d00',
  background: '#faf8ff',
  onBackground: '#191b23',
  surfaceVariant: '#e1e2ed',

  // Semantic status tints used across exam/result badges in the Stitch screens
  success: '#166534',
  successContainer: '#dcfce7',
  successContainerBorder: '#bbf7d0',
  passedBg: 'rgba(212, 237, 218, 0.5)',
  passedText: '#155724',
};

export default colors;
